name: Docker Build

on:
  push:
    branches:
      - main
      - production
    tags:
      - '*'

jobs:
  build-image:
    if: github.repository == 'HTTPArchive/almanac.httparchive.org'
    runs-on: ubuntu-latest
    name: Docker Image
    steps:
      - uses: actions/checkout@master
      - id: imgtagger
        run: |
          ghref=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///; s/refs\/heads\///')
          echo "::set-output name=imgtags::latest,$ghref"
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: httparchive/webalmanac
          tags: "${{ steps.imgtagger.outputs.imgtags }}"
